language: objective-c
matrix:
  include:
    - env: OSX=10.11
      os: osx
      osx_image: osx10.11
      rvm: system
    - env: OSX=10.10
      os: osx
      osx_image: xcode7
      rvm: system
    - env: OSX=10.9
      os: osx
      osx_image: beta-xcode6.2
      rvm: system

before_install:
  - if [ -f ".git/shallow" ]; then travis_retry git fetch --unshallow; fi
  - sudo chown -R $USER $(brew --repo)
  - brew update
  - mkdir -p $(brew --repo)/Library/Taps/mgrebenets
  - ln -s $PWD $(brew --repo)/Library/Taps/mgrebenets/mgrebenets-scan-build
  - cd $(brew --repo)/Library/Taps/mgrebenets/mgrebenets-scan-build
  - export TRAVIS_BUILD_DIR="$(brew --repo)/Library/Taps/mgrebenets/mgrebenets-scan-build"
  - env | grep TRAVIS | tee /tmp/travis.env

script:
  - brew test-bot --tap=mgrebenets/scan-build

notifications:
  email:
    on_success: never
    on_failure: always
